### ISSUE TITLE
[BUG] Shutdown does not exits the VM

### ISSUE THREAD

**Issue by ChriMarMe** [bobuhiro11/gokvm#142]
If inside VM linux:
u-root does provide `shutdown` command, and it shuts down the system, but does not exit the VM.

`shutdown -r` for rebooting leads to proper VMexit.

Which is kinda weird behaviour.

**Comment by bobuhiro11** [comment]
Thanks for bug report!
I was able to reproduce in my environment that "shutdown -r"  cause an exit with "CPU 0 exits" message,
but "shutdown" does not.

It may be related to https://github.com/bobuhiro11/gokvm/issues/87.

**Comment by ChriMarMe** [comment]
Indeed the same issue.
