### ISSUE TITLE
CI credits: Whoopsie

### ISSUE THREAD

**Issue by ChriMarMe** [bobuhiro11/gokvm#153]
Hi, I guess I pushed to the repo too much and TravisCI blocks further builds.

Is there anything I can do?

**Comment by bobuhiro11** [comment]
Thanks for letting me know!

I have requested additional OSS credits for Travis CI.
Maybe they will add it in a few days.
It's free, so don't worry about it and use it for your builds.

**Comment by bobuhiro11** [comment]
Travis CI team added OSS credits.
I have confirmed that the build can resume.

https://app.travis-ci.com/github/bobuhiro11/gokvm/jobs/605903114
